name: lykluk
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.3+12

environment:
  sdk: ^3.7.2

dependencies:
  animated_text_kit: ^4.2.3
  apivideo_player: ^1.4.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  chewie: ^1.12.1
  country_code_picker: ^3.4.1
  country_picker: ^2.0.27
  country_state_city: ^0.1.6
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dotted_border: ^3.1.0
  equatable: ^2.0.7
  ffmpeg_kit_flutter_new: ^3.2.0
  file_picker: ^10.3.3
  firebase_analytics: ^11.5.2
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  firebase_messaging: ^15.2.9
  firebase_remote_config: ^5.4.7
  firebase_storage: ^12.4.9
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_hooks: ^0.21.2
  flutter_local_notifications: ^19.4.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  flutter_svg_provider: ^1.0.7
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  geolocator: ^14.0.2
  get_it: ^8.2.0
  go_router: ^16.0.0
  google_sign_in: ^6.2.1
  hexcolor: ^3.0.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.2
  intl: any
  location: ^8.0.1
  logger: ^2.6.0
  new_version_plus: ^0.1.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pinput: ^5.0.1
  preload_page_view: ^0.2.0
  pretty_dio_logger: ^1.4.0
  riverpod: ^2.6.1
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  socket_io_client: ^3.1.2
  timeago: ^3.7.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  video_editor: ^3.0.0
  video_player: ^2.10.0
  video_uploader: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.12
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  # freezed: any
  # build_runner: ^2.4.12
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: null

dependency_overrides:
  video_thumbnail:
    path: packages/video_thumbnail-0.5.6

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#8C37C3"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svgs/
    - assets/fonts/
    - assets/images/
    - assets/BPVod.lic

  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/figtree/Figtree-Light.ttf
        - asset: assets/fonts/figtree/Figtree-LightItalic.ttf
          style: italic
        - asset: assets/fonts/figtree/Figtree-Regular.ttf
        - asset: assets/fonts/figtree/Figtree-Italic.ttf
          style: italic
        - asset: assets/fonts/figtree/Figtree-Medium.ttf
        - asset: assets/fonts/figtree/Figtree-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/figtree/Figtree-SemiBold.ttf
        - asset: assets/fonts/figtree/Figtree-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/figtree/Figtree-Bold.ttf
        - asset: assets/fonts/figtree/Figtree-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/figtree/Figtree-ExtraBold.ttf
        - asset: assets/fonts/figtree/Figtree-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/figtree/Figtree-Black.ttf
        - asset: assets/fonts/figtree/Figtree-BlackItalic.ttf
          style: italic
    - family: Bricolage
      fonts:
        - asset: assets/fonts/bricolage/BricolageGrotesque-Regular.ttf
        - asset: assets/fonts/bricolage/BricolageGrotesque-Medium.ttf
        - asset: assets/fonts/bricolage/BricolageGrotesque-Bold.ttf
        - asset: assets/fonts/bricolage/BricolageGrotesque-ExtraBold.ttf
        - asset: assets/fonts/bricolage/BricolageGrotesque-ExtraLight.ttf
        - asset: assets/fonts/bricolage/BricolageGrotesque-Light.ttf
        - asset: assets/fonts/bricolage/BricolageGrotesque-SemiBold.ttf
